-- MySQL Script generated by MySQL Workbench
-- Tue Dec 21 21:25:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AgendaPersonal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AgendaPersonal` ;

-- -----------------------------------------------------
-- Schema AgendaPersonal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AgendaPersonal` DEFAULT CHARACTER SET utf8 ;
USE `AgendaPersonal` ;

-- -----------------------------------------------------
-- Table `AgendaPersonal`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgendaPersonal`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `AgendaPersonal`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NOT NULL,
  `celular` VARCHAR(10) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgendaPersonal`.`Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgendaPersonal`.`Evento` ;

CREATE TABLE IF NOT EXISTS `AgendaPersonal`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaTermino` DATE NOT NULL,
  `lugar` VARCHAR(50) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Evento_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `AgendaPersonal`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
